### ISSUE TITLE
Commandline parameters not parsed when running OmnisTap from commandline with OmnisCli

### ISSUE THREAD

**Issue by Frogli** [PISL/omnis-launcher#1]
Dear Pisl,

Thanks for making this library available. This gave me another look on the startup of libraries with Omnis Studio. While experimenting with this I tried to get the OmnisTAP and OmnisCLI working with the OmnisTap_example library, but I do not get it to work. I was wondering did you get it to work so that the test can be started from the commandline? What I have done is the following
1. Follow the [OmnisCLI/TAP instructions](https://github.com/suransys/omnistap/wiki/Running-OmnisTAP-from-the-command-line) in order to run test. from the command line. And this does work when I put the libraries in the startup folder of the Omnis Studio Runtime.
2. I moved the libraries from the startup folder to the ~/Desktop.
3. Copied the launcher.lbs and .txt to the startup folder
4. Edited the launcher.txt (see below)
```
/Users/Frogli/Desktop/test/omniscli.lbs
/Users/Frogli/Desktop/test/omnistap.lbs 
/Users/Frogli/Desktop/test/omnistap_example.lbs
```

5. Started Omnis Studio to confirm if the libraries are loaded and the Startup_Task opened (and they were all both loaded and opened). 
6. Started a Terminal and executed the command
`/Applications/Omnis\ Studio\ 8.1.4\ x64.app/Contents/MacOS/bin/omniscli help`
Omnis Studio starts up perfectly, but the 'help' command is not parsed and acted on accordingly. Which should return the options of the test library in the console. Again this does work when I put the libraries in the startup folder.

Then I put a Breakpoint in the Startup_Task of the test library and I noticed that the environment variable OMNISCLI_ARGUMENTS is not available to Omnis. 

I hope that you can give me some pointer where I missed something and why a certain environment variable is suddenly not available in Omnis Studio.

Thanks already for looking into this!

**Comment by teneruffian** [comment]
Hi Frogli,

Just had a quick look at this and I believe the issue may be related to this method in omniscli.lbs.  The omniscli script writes stdout to the `run` folder in the same path as the folder containing the omniscli.lbs:

```
oOmnisCLI.$_getPathToRun

Calculate lcLibraryParentPath as FileOps.$parentdir($clib.$pathname)
If right(lcLibraryParentPath,1)=pathsep()
	Calculate lcLibraryParentPath as trim(lcLibraryParentPath,kFalse,kTrue,pathsep())
End If
Calculate lcStartupParentPath as FileOps.$parentdir(lcLibraryParentPath)
If right(lcStartupParentPath,1)=pathsep()
	Calculate lcStartupParentPath as trim(lcStartupParentPath,kFalse,kTrue,pathsep())
End If
Calculate lcPathToRun as con(lcStartupParentPath,pathsep(),"run")
If FileOps.$doesfileexist(lcPathToRun)=kFalse
	Do FileOps.$createdir(lcPathToRun)
End If
Quit method lcPathToRun
```

To avoid having to go into the Omnis executable tree, I put all the @suransys files in the Application Support folder.  Although I had to edit omniscli with a hardcoded path to the omnis executable. (I believe Alex may have fixed this but I haven't tested it yet.)

```
/Users/teneruffian/Library/Application Support/Omnis/Omnis CLI/bin/omniscli

/Users/teneruffian/Library/Application Support/Omnis/Omnis CLI/libs/omniscli.lbs
/Users/teneruffian/Library/Application Support/Omnis/Omnis CLI/libs/omnistap.lbs

/Users/teneruffian/Library/Application Support/Omnis/Omnis CLI/run
```

And then my other libraries can go wherever I want to put them:

```
/Users/teneruffian/Desktop/testlibs/omnisci.lbs
/Users/teneruffian/Desktop/testlibs/omnistap_example.lbs
```

Hope this helps.

**Comment by Frogli** [comment]
Closing this issue. The parameters are parsed

**Comment by Frogli** [comment]
One addition to this:
Do not not put the omniscli.lbs and omnistap.lbs path in the launcher.txt. I got the problem then that the tests are executed, but no passed/failed output to the terminal and the omniscli shell script is not finished until it has another 3 retries. This also means that the launcher.lbs/txt has to be renamed to to something like zLauncher.lbs/txt if the names of the production/test libraries are earlier in the alphabet then the OmnisCli/Tap libraries.

**Comment by teneruffian** [comment]
Hi Henk,
I haven't tried omnistap in these intervening months but I don't recall having these issues.  I will try my setup again when I can find the opportunity and get back to you.  Are you running this on Windows or macOS?

**Comment by teneruffian** [comment]
Hi Henk,
Sorry, ignore that last question.  I can see from your original message that you're running on a Mac.
Graham
